driver: mysql
source: root:112233@tcp(127.0.0.1:3306)/shop?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
out_path: query
model_pkg_path: models
data_path: data
acronyms:
#  api: API
#  id: ID
#  ip: IP
#  url: URL
#  uri: URI
#  http: HTTP
#  https: HTTPS
#  tcp: TCP
#  udp: UDP
#  rpc: RPC
#  sql: SQL
#  db: DB
#  uid: UID
#  uuid: UUID
#  sku: SKU
#  sn: SN
