// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liujitcn/shop-gorm-gen/models"
)

func newBaseApi(db *gorm.DB, opts ...gen.DOOption) baseApi {
	_baseApi := baseApi{}

	_baseApi.baseApiDo.UseDB(db, opts...)
	_baseApi.baseApiDo.UseModel(&models.BaseApi{})

	tableName := _baseApi.baseApiDo.TableName()
	_baseApi.ALL = field.NewAsterisk(tableName)
	_baseApi.ID = field.NewInt64(tableName, "id")
	_baseApi.ServiceName = field.NewString(tableName, "service_name")
	_baseApi.ServiceDesc = field.NewString(tableName, "service_desc")
	_baseApi.Desc = field.NewString(tableName, "desc")
	_baseApi.Operation = field.NewString(tableName, "operation")
	_baseApi.Method = field.NewString(tableName, "method")
	_baseApi.Path = field.NewString(tableName, "path")
	_baseApi.DeletedAt = field.NewField(tableName, "deleted_at")

	_baseApi.fillFieldMap()

	return _baseApi
}

// baseApi API信息
type baseApi struct {
	baseApiDo baseApiDo

	ALL         field.Asterisk
	ID          field.Int64  // API ID
	ServiceName field.String // 服务名
	ServiceDesc field.String // 服务描述
	Desc        field.String // 描述
	Operation   field.String // 操作方法
	Method      field.String // 请求方式
	Path        field.String // 请求地址
	DeletedAt   field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (b baseApi) Table(newTableName string) *baseApi {
	b.baseApiDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b baseApi) As(alias string) *baseApi {
	b.baseApiDo.DO = *(b.baseApiDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *baseApi) updateTableName(table string) *baseApi {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ServiceName = field.NewString(table, "service_name")
	b.ServiceDesc = field.NewString(table, "service_desc")
	b.Desc = field.NewString(table, "desc")
	b.Operation = field.NewString(table, "operation")
	b.Method = field.NewString(table, "method")
	b.Path = field.NewString(table, "path")
	b.DeletedAt = field.NewField(table, "deleted_at")

	b.fillFieldMap()

	return b
}

func (b *baseApi) WithContext(ctx context.Context) *baseApiDo { return b.baseApiDo.WithContext(ctx) }

func (b baseApi) TableName() string { return b.baseApiDo.TableName() }

func (b baseApi) Alias() string { return b.baseApiDo.Alias() }

func (b baseApi) Columns(cols ...field.Expr) gen.Columns { return b.baseApiDo.Columns(cols...) }

func (b *baseApi) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *baseApi) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 8)
	b.fieldMap["id"] = b.ID
	b.fieldMap["service_name"] = b.ServiceName
	b.fieldMap["service_desc"] = b.ServiceDesc
	b.fieldMap["desc"] = b.Desc
	b.fieldMap["operation"] = b.Operation
	b.fieldMap["method"] = b.Method
	b.fieldMap["path"] = b.Path
	b.fieldMap["deleted_at"] = b.DeletedAt
}

func (b baseApi) clone(db *gorm.DB) baseApi {
	b.baseApiDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b baseApi) replaceDB(db *gorm.DB) baseApi {
	b.baseApiDo.ReplaceDB(db)
	return b
}

type baseApiDo struct{ gen.DO }

func (b baseApiDo) Debug() *baseApiDo {
	return b.withDO(b.DO.Debug())
}

func (b baseApiDo) WithContext(ctx context.Context) *baseApiDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b baseApiDo) ReadDB() *baseApiDo {
	return b.Clauses(dbresolver.Read)
}

func (b baseApiDo) WriteDB() *baseApiDo {
	return b.Clauses(dbresolver.Write)
}

func (b baseApiDo) Session(config *gorm.Session) *baseApiDo {
	return b.withDO(b.DO.Session(config))
}

func (b baseApiDo) Clauses(conds ...clause.Expression) *baseApiDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b baseApiDo) Returning(value interface{}, columns ...string) *baseApiDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b baseApiDo) Not(conds ...gen.Condition) *baseApiDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b baseApiDo) Or(conds ...gen.Condition) *baseApiDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b baseApiDo) Select(conds ...field.Expr) *baseApiDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b baseApiDo) Where(conds ...gen.Condition) *baseApiDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b baseApiDo) Order(conds ...field.Expr) *baseApiDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b baseApiDo) Distinct(cols ...field.Expr) *baseApiDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b baseApiDo) Omit(cols ...field.Expr) *baseApiDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b baseApiDo) Join(table schema.Tabler, on ...field.Expr) *baseApiDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b baseApiDo) LeftJoin(table schema.Tabler, on ...field.Expr) *baseApiDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b baseApiDo) RightJoin(table schema.Tabler, on ...field.Expr) *baseApiDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b baseApiDo) Group(cols ...field.Expr) *baseApiDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b baseApiDo) Having(conds ...gen.Condition) *baseApiDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b baseApiDo) Limit(limit int) *baseApiDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b baseApiDo) Offset(offset int) *baseApiDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b baseApiDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *baseApiDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b baseApiDo) Unscoped() *baseApiDo {
	return b.withDO(b.DO.Unscoped())
}

func (b baseApiDo) Create(values ...*models.BaseApi) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b baseApiDo) CreateInBatches(values []*models.BaseApi, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b baseApiDo) Save(values ...*models.BaseApi) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b baseApiDo) First() (*models.BaseApi, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.BaseApi), nil
	}
}

func (b baseApiDo) Take() (*models.BaseApi, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.BaseApi), nil
	}
}

func (b baseApiDo) Last() (*models.BaseApi, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.BaseApi), nil
	}
}

func (b baseApiDo) Find() ([]*models.BaseApi, error) {
	result, err := b.DO.Find()
	return result.([]*models.BaseApi), err
}

func (b baseApiDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.BaseApi, err error) {
	buf := make([]*models.BaseApi, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b baseApiDo) FindInBatches(result *[]*models.BaseApi, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b baseApiDo) Attrs(attrs ...field.AssignExpr) *baseApiDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b baseApiDo) Assign(attrs ...field.AssignExpr) *baseApiDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b baseApiDo) Joins(fields ...field.RelationField) *baseApiDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b baseApiDo) Preload(fields ...field.RelationField) *baseApiDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b baseApiDo) FirstOrInit() (*models.BaseApi, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.BaseApi), nil
	}
}

func (b baseApiDo) FirstOrCreate() (*models.BaseApi, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.BaseApi), nil
	}
}

func (b baseApiDo) FindByPage(offset int, limit int) (result []*models.BaseApi, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b baseApiDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b baseApiDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b baseApiDo) Delete(models ...*models.BaseApi) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *baseApiDo) withDO(do gen.Dao) *baseApiDo {
	b.DO = *do.(*gen.DO)
	return b
}
