// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/liujitcn/shop-gorm-gen/models"
)

func newGoodsSKU(db *gorm.DB, opts ...gen.DOOption) goodsSKU {
	_goodsSKU := goodsSKU{}

	_goodsSKU.goodsSKUDo.UseDB(db, opts...)
	_goodsSKU.goodsSKUDo.UseModel(&models.GoodsSKU{})

	tableName := _goodsSKU.goodsSKUDo.TableName()
	_goodsSKU.ALL = field.NewAsterisk(tableName)
	_goodsSKU.ID = field.NewInt64(tableName, "id")
	_goodsSKU.GoodsID = field.NewInt64(tableName, "goods_id")
	_goodsSKU.Picture = field.NewString(tableName, "picture")
	_goodsSKU.SkuCode = field.NewString(tableName, "sku_code")
	_goodsSKU.SpecItem = field.NewString(tableName, "spec_item")
	_goodsSKU.Price = field.NewInt64(tableName, "price")
	_goodsSKU.DiscountPrice = field.NewInt64(tableName, "discount_price")
	_goodsSKU.InitSaleNum = field.NewInt64(tableName, "init_sale_num")
	_goodsSKU.RealSaleNum = field.NewInt64(tableName, "real_sale_num")
	_goodsSKU.Inventory = field.NewInt64(tableName, "inventory")
	_goodsSKU.DeletedAt = field.NewField(tableName, "deleted_at")

	_goodsSKU.fillFieldMap()

	return _goodsSKU
}

// goodsSKU 商品SKU信息
type goodsSKU struct {
	goodsSKUDo goodsSKUDo

	ALL           field.Asterisk
	ID            field.Int64  // 商品SKUID
	GoodsID       field.Int64  // 商品ID
	Picture       field.String // SKU图片
	SkuCode       field.String // SKU编码
	SpecItem      field.String // SKU 规格组成, 注意：需要与 goods_spec 数组顺序对应
	Price         field.Int64  // 当前价格(分)
	DiscountPrice field.Int64  // 折扣价格（分）
	InitSaleNum   field.Int64  // 初始销量
	RealSaleNum   field.Int64  // 真实销售数量
	Inventory     field.Int64  // 库存数量
	DeletedAt     field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (g goodsSKU) Table(newTableName string) *goodsSKU {
	g.goodsSKUDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goodsSKU) As(alias string) *goodsSKU {
	g.goodsSKUDo.DO = *(g.goodsSKUDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goodsSKU) updateTableName(table string) *goodsSKU {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.GoodsID = field.NewInt64(table, "goods_id")
	g.Picture = field.NewString(table, "picture")
	g.SkuCode = field.NewString(table, "sku_code")
	g.SpecItem = field.NewString(table, "spec_item")
	g.Price = field.NewInt64(table, "price")
	g.DiscountPrice = field.NewInt64(table, "discount_price")
	g.InitSaleNum = field.NewInt64(table, "init_sale_num")
	g.RealSaleNum = field.NewInt64(table, "real_sale_num")
	g.Inventory = field.NewInt64(table, "inventory")
	g.DeletedAt = field.NewField(table, "deleted_at")

	g.fillFieldMap()

	return g
}

func (g *goodsSKU) WithContext(ctx context.Context) *goodsSKUDo { return g.goodsSKUDo.WithContext(ctx) }

func (g goodsSKU) TableName() string { return g.goodsSKUDo.TableName() }

func (g goodsSKU) Alias() string { return g.goodsSKUDo.Alias() }

func (g goodsSKU) Columns(cols ...field.Expr) gen.Columns { return g.goodsSKUDo.Columns(cols...) }

func (g *goodsSKU) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goodsSKU) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 11)
	g.fieldMap["id"] = g.ID
	g.fieldMap["goods_id"] = g.GoodsID
	g.fieldMap["picture"] = g.Picture
	g.fieldMap["sku_code"] = g.SkuCode
	g.fieldMap["spec_item"] = g.SpecItem
	g.fieldMap["price"] = g.Price
	g.fieldMap["discount_price"] = g.DiscountPrice
	g.fieldMap["init_sale_num"] = g.InitSaleNum
	g.fieldMap["real_sale_num"] = g.RealSaleNum
	g.fieldMap["inventory"] = g.Inventory
	g.fieldMap["deleted_at"] = g.DeletedAt
}

func (g goodsSKU) clone(db *gorm.DB) goodsSKU {
	g.goodsSKUDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g goodsSKU) replaceDB(db *gorm.DB) goodsSKU {
	g.goodsSKUDo.ReplaceDB(db)
	return g
}

type goodsSKUDo struct{ gen.DO }

func (g goodsSKUDo) Debug() *goodsSKUDo {
	return g.withDO(g.DO.Debug())
}

func (g goodsSKUDo) WithContext(ctx context.Context) *goodsSKUDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goodsSKUDo) ReadDB() *goodsSKUDo {
	return g.Clauses(dbresolver.Read)
}

func (g goodsSKUDo) WriteDB() *goodsSKUDo {
	return g.Clauses(dbresolver.Write)
}

func (g goodsSKUDo) Session(config *gorm.Session) *goodsSKUDo {
	return g.withDO(g.DO.Session(config))
}

func (g goodsSKUDo) Clauses(conds ...clause.Expression) *goodsSKUDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goodsSKUDo) Returning(value interface{}, columns ...string) *goodsSKUDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goodsSKUDo) Not(conds ...gen.Condition) *goodsSKUDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goodsSKUDo) Or(conds ...gen.Condition) *goodsSKUDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goodsSKUDo) Select(conds ...field.Expr) *goodsSKUDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goodsSKUDo) Where(conds ...gen.Condition) *goodsSKUDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goodsSKUDo) Order(conds ...field.Expr) *goodsSKUDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goodsSKUDo) Distinct(cols ...field.Expr) *goodsSKUDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goodsSKUDo) Omit(cols ...field.Expr) *goodsSKUDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goodsSKUDo) Join(table schema.Tabler, on ...field.Expr) *goodsSKUDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goodsSKUDo) LeftJoin(table schema.Tabler, on ...field.Expr) *goodsSKUDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goodsSKUDo) RightJoin(table schema.Tabler, on ...field.Expr) *goodsSKUDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goodsSKUDo) Group(cols ...field.Expr) *goodsSKUDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goodsSKUDo) Having(conds ...gen.Condition) *goodsSKUDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goodsSKUDo) Limit(limit int) *goodsSKUDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goodsSKUDo) Offset(offset int) *goodsSKUDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goodsSKUDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *goodsSKUDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goodsSKUDo) Unscoped() *goodsSKUDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goodsSKUDo) Create(values ...*models.GoodsSKU) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goodsSKUDo) CreateInBatches(values []*models.GoodsSKU, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goodsSKUDo) Save(values ...*models.GoodsSKU) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goodsSKUDo) First() (*models.GoodsSKU, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsSKU), nil
	}
}

func (g goodsSKUDo) Take() (*models.GoodsSKU, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsSKU), nil
	}
}

func (g goodsSKUDo) Last() (*models.GoodsSKU, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsSKU), nil
	}
}

func (g goodsSKUDo) Find() ([]*models.GoodsSKU, error) {
	result, err := g.DO.Find()
	return result.([]*models.GoodsSKU), err
}

func (g goodsSKUDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.GoodsSKU, err error) {
	buf := make([]*models.GoodsSKU, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goodsSKUDo) FindInBatches(result *[]*models.GoodsSKU, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goodsSKUDo) Attrs(attrs ...field.AssignExpr) *goodsSKUDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goodsSKUDo) Assign(attrs ...field.AssignExpr) *goodsSKUDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goodsSKUDo) Joins(fields ...field.RelationField) *goodsSKUDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goodsSKUDo) Preload(fields ...field.RelationField) *goodsSKUDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goodsSKUDo) FirstOrInit() (*models.GoodsSKU, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsSKU), nil
	}
}

func (g goodsSKUDo) FirstOrCreate() (*models.GoodsSKU, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsSKU), nil
	}
}

func (g goodsSKUDo) FindByPage(offset int, limit int) (result []*models.GoodsSKU, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goodsSKUDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goodsSKUDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goodsSKUDo) Delete(models ...*models.GoodsSKU) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goodsSKUDo) withDO(do gen.Dao) *goodsSKUDo {
	g.DO = *do.(*gen.DO)
	return g
}
